# Generated by Django 3.0.4 on 2020-03-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200324_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='user',
            new_name='owner',
        ),
    ]
