# Generated by Django 3.0.4 on 2020-03-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20200310_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
