# Generated by Django 3.0.4 on 2020-03-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200324_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Recipe'),
        ),
    ]
