# Generated by Django 3.0.4 on 2020-04-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200407_1417'),
        ('recipes', '0010_recipe_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
